source 'https://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'site_prism'
gem 'selenium-webdriver'
gem 'rspec'
gem 'ruby-gmail'
gem 'chronic'
gem 'rest_client'
gem 'show_me_the_cookies'
gem 'poltergeist'
gem 'capybara-screenshot'
gem 'rake'